31
lkhalilova/python_dev pull request #16
Opened 2023-04-15 23:55 UTC by lkhalilova

2023-04-17 19:55 UTC, klymenok reviewed
директорії .idea та __pycache__ не мають додаватися на git

2023-04-17 19:56 UTC, klymenok requested changes

2023-04-17 19:56 UTC, klymenok commented on Django/requirements
Зайвий файл

2023-04-17 19:56 UTC, klymenok commented on Django/requirements.txt
Пустий файл

2023-04-17 19:56 UTC, klymenok commented on hm_30/hm_030.py
Файл не стосуєтьстя ДЗ

2023-04-23 22:01 UTC, lkhalilova commented on hm_30/hm_030.py
не бачу де ви побачили цю директорію

2023-04-25 18:02 UTC, klymenok commented on hm_30/hm_030.py
<img width="339" alt="image" src="https://user-images.githubusercontent.com/18496465/234363131-af5a46ce-7a53-4b15-b84c-70a0a51388ed.png">

2023-04-25 18:02 UTC, klymenok commented on hm_30/hm_030.py
<img width="359" alt="image" src="https://user-images.githubusercontent.com/18496465/234363309-01322155-7eb6-4017-8979-21bfa5c06614.png">

2023-04-25 18:04 UTC, klymenok commented on Django/requirements.txt
Додайте сюди бібліотеки, що ви встановили в віртуальному середовищі: `pip freeze > requirements.txt`

2023-04-28 00:29 UTC, lkhalilova commented on hm_30/hm_030.py
Ось я відкриваю гілку 31 на гітхаб, і в ній директорія django з усіма іншими дз,що були до цього. Я не бачу цієї директорії
![Untitled](https://user-images.githubusercontent.com/121033230/235022484-e6412953-a2de-4d2b-bf87-1bff74e24951.png)

2023-05-01 10:18 UTC, klymenok commented on hm_30/hm_030.py
Добре. Можливо це баг GitHub

2023-05-01 17:39 UTC, lkhalilova commented on Django/requirements.txt
так я їх і додала)

2023-05-03 11:04 UTC, klymenok approved these changes

2023-05-06 18:04 UTC, merged